### ISSUE TITLE
Karoo 2 FIT files are not correctly converted to GPX

### ISSUE THREAD

**Issue by presslab-us** [eneiluj/gpxpod#18]
I have some FIT files from a Hammerhead Karoo 2 that I've uploaded to the Nextcloud folder.  When I open this folder in Gpxpod I can see new GPX files being created in the same folder but these files are zero size.

When I open that folder in the terminal and execute for example:
```
gpsbabel -i garmin_fit -o gpx f4851544-c3e3-42db-8665-5a7715dea415.fit f4851544-c3e3-42db-8665-5a7715dea415.gpx
```
then the GPX file is correctly created and I can open it in Gpxpod.

I didn't see anything in the Nextcloud log indicating any problems, other than:
```
Exception in f63a27f9-788a-4483-b47f-f3398fb9fcbc.gpx gpx parsing : String could not be parsed as XML
```
which is likely just Gpxpod trying to open the zero size files.

I put a bit of debug code in Gpxpod and I can see the parameters sent to gpsbabel are:
```
/usr/bin/gpsbabel -i garmin_fit -f - -o gpx -F -
```
and the stderr output was:
```
fit: This format cannot be used in piped commands!
```
which looks to come from this line of code:
https://github.com/GPSBabel/gpsbabel/blob/7da564a27e7d664dd0bf5924d6651f6d0a626084/gbfile.cc#L134

My guess is that there is something in the FIT files which requires seeking inside the data, and by using the piped input this is not supported.

**Comment by presslab-us** [comment]
The patch below solves the problem for me.  I know this fix is not correct but it's just to show that passing the file instead of using a pipe is working.
```
--- OldPageController.php.orig
+++ OldPageController.php
@@ -728,11 +728,11 @@
 								$content = $f->getContent();
 
 								if ($igcfilter1 !== '') {
-									$args = ['-i', $gpsbabel_fmt, '-f', '-',
+									$args = ['-i', $gpsbabel_fmt, '-f', '/mnt/ncdata' . $gpx_targetfolder->getPath() . '/' . $name,
 										$igcfilter1, $igcfilter2, '-o',
 										'gpx', '-F', '-'];
 								} else {
-									$args = ['-i', $gpsbabel_fmt, '-f', '-',
+									$args = ['-i', $gpsbabel_fmt, '-f', '/mnt/ncdata' . $gpx_targetfolder->getPath() . '/' . $name,
 										'-o', 'gpx', '-F', '-'];
 								}
 								$cmdparams = '';
@@ -751,8 +751,8 @@
 									$pipes
 								);
 								// write to stdin
-								fwrite($pipes[0], $content);
-								fclose($pipes[0]);
+								//fwrite($pipes[0], $content);
+								//fclose($pipes[0]);
 								// read from stdout
 								$gpx_clear_content = stream_get_contents($pipes[1]);
 								fclose($pipes[1]);

```

**Comment by julien-nc** [comment]
Hey, thanks for the bug report. This is quite a bad idea to run GpsBabel in GpxPod anyway. I'd like to get away for that.
It turns out I found a nice Php library to parse FIT files and used it to implement my own FIT to GPX converter in pure Php.
The nice thing about it is to control exactly what is written in the result GPX files, like the huge amount of additional data potentially provided by the FIT format (speed, temperature, heart rate etc...). After being quite happy about the converter, it was natural to implement the feature allowing to select any extension value as a track color criteria.

![image](https://user-images.githubusercontent.com/11291457/229388029-05afa127-0b51-4678-8712-aa0a12b61f74.png)

Could you try [v5.0.7-2-nightly](https://github.com/julien-nc/gpxpod/releases/download/v5.0.7-2-nightly/gpxpod-5.0.7-2-nightly.tar.gz)? As it contains database changes, I would recommend to use it on a test instance only. Anyway, the data stored in GpxPod's tables is not very important and can be computed again...
You can also wait for the next release which is coming soon.

I would be interested to get one or more of your FIT files to check if they are supported by the new converter.

**Comment by presslab-us** [comment]
Thanks a lot! I have tested v5.0.7-2 and it is now working great with the Karoo 2 FIT files.

The track coloring is a very welcome addition as well. Would it be difficult to also allow selecting whatever extension criteria that are contained in the FIT file? The Karoo also has `Temperature` which is working when I type it in the text box.  I would guess it would have heart rate too (if I had worn my monitor).  Putting these extension criteria into the charts would be fantastic as well, maybe with an option to turn them off and on.

I'd be happy to send you some FIT files but I don't want to attach them here as they show my house location.

Again thanks very much!

**Comment by julien-nc** [comment]
Thanks for the feedback and the enthusiasm!

I don't need examples tracks from you now. If it works for you and me with FIT files coming from different devices, it's good enough.

If you need to send me some "private" stuff in the future, my email address comes with every commit of this repository.

> Putting these extension criteria into the charts would be fantastic as well, maybe with an option to turn them off and on.

This is indeed the best next thing to do with extensions. It's done and available in [v5.0.8-1-nightly](https://github.com/julien-nc/gpxpod/releases/download/v5.0.8-1-nightly/gpxpod-5.0.8-1-nightly.tar.gz). It would again be awesome if you could give it a try.

![image](https://user-images.githubusercontent.com/11291457/229582346-0856e6cb-e593-4cde-96c0-632e64daa9d0.png)

**Comment by presslab-us** [comment]
Cool, with v5.0.8 I can plot the other fields on the chart, thanks!

I noticed something with the track coloring, on some of the data fields (this is speed) when I zoom out there are gaps in the track.
![image](https://user-images.githubusercontent.com/5122115/229592078-a4f40c06-fb90-45c6-bacd-4bdeffba5d6e.png)

On others (like elevation) the track is continuous but the color changes to black in some sections, again once I zoom in the black color then goes back to normal.  It doesn't seem to matter what map source I use but I do notice that it seems to correlate with the map detail level.
![image](https://user-images.githubusercontent.com/5122115/229592007-02448133-58f1-4e15-8e45-9593dc61d739.png)

**Comment by julien-nc** [comment]
Hey, thanks again for the feedback :blue_heart: 

About the track glitches, it's because there is no perfect way to draw colorized lines in MapLibre. It's impossible to use point properties when using a line gradient. So the way it's implemented in GpxPod is a bit...overkill. Depending on the criteria, it sometimes uses multiple features in a single layer or even one feature (segment) per layer. This actually draws many elements and MapLibre behaves weirdly when zooming out.

I gave it another thought and decided to reimplement that part in a simpler fashion. It is possible to give a list of steps to the color gradient. It was quite hard to compute but now it's much better and the glitch is gone because there is just one feature in one layer for each track segment.

While I was on this. I added a setting to choose whether to use the global min/max or the segment-specific ones to compute the colors. It is useful only if you have files with multiple segments.

It would be again very useful and nice if you could try [v5.0.8-2-nightly](https://github.com/julien-nc/gpxpod/releases/download/v5.0.8-2-nightly/gpxpod-5.0.8-2-nightly.tar.gz). The next release is coming soon anyway.

**Comment by presslab-us** [comment]
Looks smooth now, very satisfying. :+1:   I've been playing with the colorization and it's a great addition, it gives a good insight into the data.

It sounds like the `Colorize track segments based on the global track data` is only "global" for one track log (with multiple segments), and not for multiple tracks on the screen at once?

This is what I mean: Here it's coloring based on elevation with the above setting.  There are two overlapping tracks and you can see where one stops and the color abruptly changes to the other one.
![image](https://user-images.githubusercontent.com/5122115/229918069-62367918-f305-433d-b720-3200f9b8334d.png)

**Comment by julien-nc** [comment]
Hey.

> It sounds like the Colorize track segments based on the global track data is only "global" for one track log (with multiple segments), and not for multiple tracks on the screen at once?

Yes indeed.
By global I mean considering all segments in one track.
I don't mean every track currently displayed. I think this would be weird, not so useful, hard to implement and too costly to compute when a lot of tracks are displayed. It would also be necessary to redraw every track each time a new one is added, to recompute the colors.

What do you think?

If someone has one recording divided in multiple tracks, then it makes sense to combine those tracks into one with an editor.

We could close this issue soon. We've slipped away from the original topic too much :grin:.

**Comment by presslab-us** [comment]
I can see how it could be nice to compare different tracks using the coloring but I'm not sure it's really needed.  For example it would be easy to compare elevation change from one track to a different one.  Maybe it's possible to just clarify the wording in the map settings option.

Thanks again for your help!  I will close this issue now. :+1:
