### ISSUE TITLE
Error when trying to add directory

### ISSUE THREAD

**Issue by derEremit** [eneiluj/gpxpod#6]
`Failed to add directory: Impossible to insert. An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_open' in 'field list'`

NC  25.0.1

I already tried occ update again

**Comment by julien-nc** [comment]
It seems the database migration step was not executed when upgrading GpxPod.

* Which version of GpxPod is now installed?
* How did you upgrade?
* Could you run this SQL query? `SELECT * FROM oc_migrations WHERE app="gpxpod";`
* And `SELECT * FROM oc_gpxpod_directories LIMIT 1;`

**Comment by umgfoin** [comment]
There seems to be an issue with db-schema upgrades, if you already upgraded to 5.0.1.

As a workaround,, you can correct the schema manually from the db-ci-client:
`ALTER TABLE oc_gpxpod_directories RENAME COLUMN open TO is_open;`
++umgfoin

**Comment by umgfoin** [comment]
@julien-nc  (I had the same issue)
```
nc=# SELECT * FROM oc_migrations WHERE app='gpxpod';
  app   |         version
--------+--------------------------
 gpxpod | 040200Date20200317173846
 gpxpod | 040200Date20200317174315
 gpxpod | 040202Date20200602143603
 gpxpod | 050000Date20220730004531
(4 rows)
```

**Comment by derEremit** [comment]
Which version of GpxPod is now installed?
5.0.2

How did you upgrade?
I am not 100% sure but I think this could be the first time install for me, about 2 weeks ago. ( after already upgraded to nextcloud 25 )
so I do not have tried it before today actually

MariaDB [nextcloud]> SELECT * FROM oc_migrations WHERE app="gpxpod";
+--------+--------------------------+
| app    | version                  |
+--------+--------------------------+
| gpxpod | 040200Date20200317173846 |
| gpxpod | 040200Date20200317174315 |
| gpxpod | 040202Date20200602143603 |
| gpxpod | 050000Date20220730004531 |
+--------+--------------------------+

SELECT * FROM oc_gpxpod_directories LIMIT 1;
Empty set (0.000 sec)

**Comment by julien-nc** [comment]
Thank you both for the feedback.

* Was there any error displayed during install/upgrade?
* Are you sure you didn't install any nightly build?

I think the only explanation for this issue is that the 050000Date20220730004531 migration has run before it was released (most likely because a nightly was installed). I should have renamed it to make sure the "final" migration would run.

**Comment by julien-nc** [comment]
As none of the data stored in GpxPod's tables is really important, could one of you:
* uninstall/disable GpxPod v5.0.2
* delete the oc_gpxpod_* tables
* run `DELETE FROM oc_migrations WHERE app="gpxpod" AND version="050000Date20220730004531";`
* install/enable GpxPod
* check if adding a directory works

I want to know if the issue is related with something specific in your setup or if I was right about the nightly :grin:.

**Comment by umgfoin** [comment]
Bonjour Julien,
> I think the only explanation for this issue is that the 050000Date20220730004531 migration has run before it was released (most likely because a nightly was installed). 

Yes this was the case with my installation: I had installed nightly builds.

> As none of the data stored in GpxPod's tables is really important, could one of you:

Yes, fails with  `Error: Database error when running migration 050000Date20220730004531 for app gpxpod
There is no table with name 'nc.oc_gpxpod_directories' in the schema.`

I renamed tables instead of deleting them, but this should not be the cause for the migration-failure.
```
# occ app:disable gpxpod
gpxpod 5.0.2 disabled

psql nc foo
psql (15.1 (xxxxxx15.1-1.xxxx))
Type "help" for help.
nc=# \dt oc_gpxpod_*
                   List of relations
 Schema |           Name           | Type  |   Owner
--------+--------------------------+-------+-----------
 public | oc_gpxpod_directories    | table | foo
 public | oc_gpxpod_options_values | table | foo
 public | oc_gpxpod_pictures       | table | foo
 public | oc_gpxpod_tile_servers   | table | foo
 public | oc_gpxpod_tracks         | table | foo
(5 rows)
nc=#ALTER TABLE oc_gpxpod_directories RENAME TO oc_gpxpod_directories_;
ALTER TABLE 
nc=#ALTER TABLE oc_gpxpod_options_values RENAME TO oc_gpxpod_options_values_;
ALTER TABLE 
nc=#ALTER TABLE oc_gpxpod_pictures RENAME TO oc_gpxpod_pictures_;
ALTER TABLE 
nc=#ALTER TABLE oc_gpxpod_tile_servers RENAME TO oc_gpxpod_tile_servers_;
ALTER TABLE 
nc=#ALTER TABLE oc_gpxpod_tracks RENAME TO oc_gpxpod_tracks_;
ALTER TABLE 

nc=# DELETE FROM oc_migrations WHERE app='gpxpod' AND version='050000Date20220730004531';
DELETE 1
nc=#\q

occ app:remove gpxpod
gpxpod disabled
gpxpod 0 removed

occ app:install gpxpod
Error: Database error when running migration 050000Date20220730004531 for app gpxpod
There is no table with name 'nc.oc_gpxpod_directories' in the schema.

**Comment by julien-nc** [comment]
Sorry you need to remove all oc_migrations entries for gpxpod:
`DELETE FROM oc_migrations WHERE app="gpxpod";`
Then you will run all the migration steps again.

**Comment by julien-nc** [comment]
@derEremit Could you try upgrading to v5.0.3 which I just released? It will appear in an hour or so in the app settings of your NC instance.

**Comment by umgfoin** [comment]
> `DELETE FROM oc_migrations WHERE app="gpxpod";`

Yes, this worked - app install was successful and db-schema is correct.
++umgfoin.

**Comment by derEremit** [comment]
@julien-nc just seen the upgrade

i can add the directory now

another thing
with 5.0.2 ../old-ui did not work

now only ../old-ui works

**Comment by julien-nc** [comment]
> another thing
> with 5.0.2 ../old-ui did not work

@derEremit What do you mean? It didn't display anything?
So you confirm everything works now?

**Comment by laurensbl** [comment]
I don't know if this is related:
I just upgraded from NC 24.0.7 to 25.0.1 and GpxPod automatically updated to 5.0.3 during the process.

Now, no tracks and/or pictures are displayed anymore in the old UI, but they do in the new UI. This is for a user that had dirs added prior to upgrading to NC 25.
I tried removing and re-adding the dirs to no avail. Same problem, nothing with old UI, all visible in new UI.

After adding the same dirs under a user (dedicated admin user) that didn't had any dirs added prior to upgrading to NC 25 however, the tracks and pictures are shown in both old and new UI.

I tried steps outlined above: Removed app, deleted oc_gpxpod_* tables, ran `DELETE FROM oc_migrations WHERE app="gpxpod";`, downloaded and installed app again. Didn't fix it either.

**Comment by julien-nc** [comment]
@laurensbl Yes this might be related. I need more information:
* any error displayed in the old-ui when loading a track?
* any network error?
* any error in the javascript console?

I don't get how directories added before the upgrade are problematic after in the old-ui and then you delete the tables, reinstall the app and you still havve issues. This means even the directories added after the upgrade are problematic...right?

**Comment by umgfoin** [comment]
> @derEremit 
> now only ../old-ui works

If you were on a nightly-build before, it should resolve with #7 .

**Comment by laurensbl** [comment]
> @laurensbl Yes this might be related. I need more information:
> 
>     * any error displayed in the old-ui when loading a track?
Nope, none 
>     * any network error?
Also none. Tracks are stored locally btw, and maps are loaded quick and smoothly. Switching between maps (OpenStreetMap and ESRI Aerial) also works. Only no tracks or pics shown.
>     * any error in the javascript console?
Under the "new user", where tracks and pics are displayed properly, I get one error:
`The resource from “https://cloud.domain.tld/apps/viewer/js/viewer.js?v=0b12e399-74” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).[old-ui](https://cloud.domain.tld/apps/gpxpod/old-ui)`
Under the "old user", I get the same error, and also a new one:
`XHR POST https://cloud.domain.tld/apps/gpxpod/tracks-old {"message":"Logged in user must be an admin"}`
> 
> I don't get how directories added before the upgrade are problematic after in the old-ui and then you delete the tables, reinstall the app and you still havve issues. This means even the directories added after the upgrade are problematic...right?

Indeed. I tried to remove and re-add the dirs several times, in Firefox and Edge (both up-to-date, Win10). After freshly adding the dirs, under the "old user" the busy indicator upper right flashes very shortly when I select a dir and shows nothing, while under the new user the animation plays for a ~ 10 secs before the dir is loaded (104 tracks) and all tracks are shown.

Well, it probably has something to do with the error I noticed in the console. The "new user" is a NC admin while "old user" is a regular user.

Edit: Note that I have updated GpxPod from NC21 to 24 without any of these problems and I also tested if the tracks are readable and not corrupted; when I click a track in the "Files" section it is opened and shown correctly in GpxPod, in the new UI. I don't know how to try to open it in the old UI from the Files section.

**Comment by laurensbl** [comment]
Tested and it does have something to do with admin rights; I added the "old user" (regular user) to the admin group and the tracks and pics are displayed in the old UI. After removing admin rights the tracks/pics are not displayed anymore.

**Comment by julien-nc** [comment]
@laurensbl Thanks for the feedback. There were indeed some mistakes restricting some API endpoints to admin users. It should be all good in v5.0.4 which is out.

v5.0.4 also includes #7 from @umgfoin making sure there is no more trouble for those having installed a recent nightly build.

I'm half sad there were errors in the v5.0.0 release and half happy we found them all so quickly. Thanks a lot for your help. I hope you'll like the new UI. It's not definitive but definitely more modern than the old one. It will be easier to maintain and (I hope) easier for contributors to add crazy features.

@laurensbl Let's close this issue once you confirm the old and new UI work fine with v5.0.4

**Comment by laurensbl** [comment]
Yep, fixed. Tracks and pics are back. Old and new UI work fine now.

The new UI is neat. Although I can't seem to draw a track via the big blue dot in de map. But I haven't used it much yet, so I might be overlooking somethings. I'll give feedback if I encounter any issues or wishes, if you like.

Thanks very much for this great app!

Edit: Btw, is there any chance ESRI Aerial can be made available in the new UI?

**Comment by derEremit** [comment]
for me with 5.0.4 now also both ui versions are accessible
"If you were on a nightly-build before..."
probably

**Comment by umgfoin** [comment]
> I'm half sad there were errors in the v5.0.0 release and half happy we found them all so quickly. Thanks a lot for your help. 

Thank you @julien-nc for your work on this really great piece of software and no less for your other "useful" contributions to the nextcloud-ecosystem:
I honour your huge effort and most of them became very quickly essential apps (atleast for me). 
> I hope you'll like the new UI. It's not definitive but definitely more modern than the old one. It will be easier to maintain and (I hope) easier for contributors to add crazy features.

Definitely appreciated!

**Comment by julien-nc** [comment]
:blue_heart: to all of you
